shell: misc bash cleanup to pass shellcheck

diff --git a/shell_common b/shell_common
--- a/shell_common
+++ b/shell_common
@@ -12,11 +12,6 @@ alias sl='ls'
 alias grep='grep --color=auto'
 alias fgrep='fgrep --color=auto'
 alias unmount='umount'
-alias path='echo -e ${PATH//:/\\n}' #print all executable paths
-alias gopath='cd "$GOPATH"'
-function accio {
-  ls -A | grep -i $1
-}
 eval "$(zoxide init zsh)"
 
 #
@@ -43,9 +38,9 @@ function v() {
 # fd - cd to selected directory
 function fd() {
   local dir
-  dir=$(find ${1:-.} -path '*/\.*' -prune \
+  dir=$(find "${1:-.}" -path '*/\.*' -prune \
                   -o -type d -print 2> /dev/null | fzf +m) &&
-  cd "$dir"
+  cd "$dir" || return
 }
 
 # fkill - kill process
@@ -55,7 +50,7 @@ function fkill() {
 
   if [ "x$pid" != "x" ]
   then
-    echo $pid | xargs kill -${1:-9}
+    echo "$pid" | xargs kill "-${1:-9}"
   fi
 }
 
@@ -69,24 +64,24 @@ export CLICOLOR=1
 export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
 
 # Extract most known archives with one command
-function extract () {
+function extract() {
   if [[ ! -f "$1" ]]
   then
      echo "'$1' is not a valid file"
   else
-    case $1 in
-      *.tar.bz2)   tar xjf $1     ;;
-      *.tar.gz)    tar xzf $1     ;;
-      *.bz2)       bunzip2 $1     ;;
-      *.rar)       unrar e $1     ;;
-      *.gz)        gunzip $1      ;;
-      *.tar)       tar xf $1      ;;
-      *.tbz2)      tar xjf $1     ;;
-      *.tgz)       tar xzf $1     ;;
-      *.zip)       unzip $1       ;;
-      *.Z)         uncompress $1  ;;
-      *.7z)        7z x $1        ;;
-      *)     echo "'$1' cannot be extracted via `extract`" ;;
+    case "$1" in
+      *.tar.bz2)   tar xjf "$1"     ;;
+      *.tar.gz)    tar xzf "$1"     ;;
+      *.bz2)       bunzip2 "$1"     ;;
+      *.rar)       unrar e "$1"     ;;
+      *.gz)        gunzip "$1"      ;;
+      *.tar)       tar xf "$1"      ;;
+      *.tbz2)      tar xjf "$1"     ;;
+      *.tgz)       tar xzf "$1"     ;;
+      *.zip)       unzip "$1"       ;;
+      *.Z)         uncompress "$1"  ;;
+      *.7z)        7z x "$1"        ;;
+      *)     echo "'$1' cannot be extracted 'extract'" ;;
     esac
   fi
 }
@@ -107,7 +102,7 @@ function remotecert() {
 function findreplace() {
   match="$1"
   replacement="$2"
-  find . -type f -exec sed -i '' s/${match}/${replacement}/g {} +
+  find . -type f -exec sed -i '' s/"${match}"/"${replacement}"/g {} +
 }
 
 #
@@ -145,5 +140,5 @@ export PATH=$PATH:$GOBIN
 #
 if [[ -f $HOME/.shell_extra ]]
 then
-  source $HOME/.shell_extra
+  source "$HOME/.shell_extra"
 fi
